defaults:
  - scope:
      path: "*"
    values:
      layout: default

title: "Блог Игоря"
author: "Игорь Цалко"
email: git@tsobako.me
theme: jekyll-theme-mint
blog_theme: auto
url: http://blog.tsobako.me

github_username: tsobako
twitter_username: tsobako
disqus_shortname: "blog-tsobako-me"

plugins:
  - jekyll-feed
