defaults:
  - scope:
      path: "*"
    values:
      layout: default

title: "Блог Игоря"
author: "Игорь Цалко"
email: git@tsobako.me
theme: jekyll-theme-mint
blog_theme: auto

github_username: tsobako
twitter_username: tsobako
disqus_shortname: tsobako

plugins:
  - jekyll-feed
